### ISSUE TITLE
Implementation plan.

### ISSUE THREAD

**Issue by abuhenasobuj** [sasalatart/on-this-day-android#1]
Hello, I don't know English language very well. Can you try to understand this image.

- **Default Screen** (_MainActivity_). / {`Will show Everyday's Episode.`}
- **Date Selection** (_SecondActivity_) / {`User can select different date and MainActivity will show that specific date Episode`}
- **Action Menu** (_Share, Bookmark_) / {`User can share, bookmark, copy each event item.`}

![On This Day Android App - Implementation plan.](https://cloud.githubusercontent.com/assets/16954436/23933059/14dd8b52-0966-11e7-8172-777f1a80acf1.png)

@sasalatart

**Comment by sasalatart** [comment]
It looks like a nice improvement. I will implement it in a few weeks time, since right now I am a bit busy. Thanks!

**Comment by abuhenasobuj** [comment]
Glad to hear that. Best wishes... `Stay good.`
